stages:
  - test

test-job:
  stage: test
  script: 
    - echo "spring"
    - echo "Второй этап"
    - echo "The end"


# stages:
#   - validate
#   - test

# variables:
#   DJANGO_SETTINGS_MODULE: "shopproject.settings"
#   VENV_PATH: ".venv"

# validate-django-settings:
#   stage: validate
#   before_script:
#     - python3 -m venv $VENV_PATH
#     - source $VENV_PATH/bin/activate
#     - pip install --upgrade pip
#     - pip install -r requirements.txt
#   script:
#     - echo "Проверка настроек Django"
#     - python3 manage.py check
#     - echo "Настройки Django валидны"

# validate-migrations:
#   stage: validate
#   before_script:
#     - python3 -m venv $VENV_PATH
#     - source $VENV_PATH/bin/activate
#     - pip install --upgrade pip
#     - pip install -r requirements.txt
#   script:
#     - echo "Проверка миграций Django"
#     - python3 manage.py makemigrations --check --dry-run
#     - echo "Миграции Django валидны"

# test-staticfiles:
#   stage: test
#   before_script:
#     - python3 -m venv $VENV_PATH
#     - source $VENV_PATH/bin/activate
#     - pip install --upgrade pip
#     - pip install -r requirements.txt
#   script:
#     - echo "Проверка статик-файлов Django"
#     - python3 manage.py collectstatic --noinput --dry-run
#     - echo "Статические Django файлы проверены"